namespace Nabto.Client.Interop
{
    internal enum NabtoStatus
    {
        Ok,
        NoProfile,
        ErrorReadingConfig,
        ApiNotInitialized,
        InvalidSession,
        OpenCertificateOrPrivateKeyFailed,
        UnlockPrivateKeyFailed,
        PortalLogInFailure,
        CertificateSigningError,
        CertificateSavingFailure,
        AddressInUse,
        InvalidAddress,
        NoNetwork,
        ConnectToHostFailed,
        StreamingUnsupported,
        InvalidStream,
        DataPending,
        BufferFull,
        Failed,
        InvalidTunnel,
        IllegalParameter,
        InvalidResource,
        InvalidStreamOption,
        InvalidStreamOptionArgument,
        Aborted,
        StreamClosed,
                FailedWithJsonMessage,
        ErrorCodeCount
    }
}
